# Set up the default terminal
ENV["TERM"] = "linux"

# Require minimum Vagrant version
Vagrant.require_version ">= 2.2.4"

Vagrant.configure("2") do |config|

  config.vm.provider "docker" do |d|
    d.image = "registry.opensuse.org/opensuse/leap:15.6"
    d.has_ssh = true
    d.remains_running = true
    d.cmd = ["sleep", "infinity"]
  end

  config.vm.provision "shell", inline: <<-SHELL
    zypper refresh
    zypper install -y apparmor-parser
  SHELL

  config.vm.network "forwarded_port", guest: 8080, host: 8080
  config.vm.network "forwarded_port", guest: 6111, host: 6111
  config.vm.network "forwarded_port", guest: 6112, host: 6112

end
